title: Andrew Graves Data Analyst
description: > # this means to ignore newlines until "baseurl:"
  Write an awesome description for your new site here. You can edit this
  line in _config.yml. It will appear in your document head meta (for
  Google search results) and in your feed.xml site description.
permalink: ':title/'
baseurl: #"/awgraves.github.io" # the subpath of your site, e.g. /blog
url: "http://awgraves.github.io" # the base hostname & protocol for your site, e.g. http://example.com
site-twitter: #if your site has a twitter account, enter it here

# Author Settings
author: Andrew Graves
author-img: light.jpg # add your photo
about-author: I am a self-taught data analyst with a social science background.
twitter: AWG_DS
facebook: # add your Facebook handle
github: awgraves # add your Github handle
linkedin: # add your Linkedin handle
email: andrewgraves92@gmail.com # add your Email address

# Disqus
discus-identifier: #mr-brown # add your discus identifier

# Tracker
analytics: # Google Analytics

# Build Settings
markdown: kramdown
plugins:
  - jekyll-sitemap
  - jekyll-paginate
  - jemoji

paginate: 8
paginate_path: "/page/:num"

exclude: ["node_modules", "gulpfile.js", "package.json", "yarn.lock"]
