title:             Data Science
email:             andrewgraves92@gmail.com
description:       A Collection of Data Science Projects
author:            Andrew Graves
baseurl:           "/awgraves"
url:               "http://awgraves.github.io"

# Social Profiles
twitter_username:  AWG_DS
github_username:   awgraves
facebook_username: StartBootstrap

# Build settings
markdown:          kramdown
paginate:          5
paginate_path:     "/posts/page:num/"
plugins:
  - jekyll-feed
  - jekyll-paginate
